Repository ekumlin/covid-employer-response, pull requests merged in 2020-04, with the labels that each got.

#49 Improve browser compat and employer info display
  README.md
  public/employers/3m.yml
  public/employers/airbnb.yml
  public/employers/amazon.yml
  public/employers/costco.yml
  public/employers/dominos.yml
  public/employers/fedex.yml
  public/employers/gamestop.yml
  public/employers/google.yml
  public/employers/hobby-lobby.yml
  public/employers/mcdonalds.yml
  public/employers/microsoft.yml
  public/employers/sample.yml
  public/employers/starbucks.yml
  public/employers/target.yml
  public/employers/tesla.yml
  public/employers/united-airlines.yml
  public/employers/walmart.yml
  public/strings/en-us.json
  src/__tests__/employer-records.test.ts
  src/common/EmployerLocation.test.ts
  src/common/EmployerLocation.ts
  src/common/LocalizedStrings.ts
  src/server.tsx
  src/web/views/Dimensions.scss
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.tsx
  src/web/views/EmployerListSearch/EmployerListFilterControl/EmployeeCountFilterControl.test.tsx
  src/web/views/EmployerListSearch/EmployerListFilterControl/EmployeeCountFilterControl.tsx
  src/web/views/EmployerListSearch/EmployerListFilterControl/EmployerListFilterControl.scss
  src/web/views/EmployerListSearch/EmployerListFilterControl/EmployerListFilterControl.tsx
  src/web/views/EmployerListSearch/EmployerListFilterControl/InternationalTypeFilterControl.test.tsx
  src/web/views/EmployerListSearch/EmployerListFilterControl/InternationalTypeFilterControl.tsx
  src/web/views/EmployerListSearch/EmployerListSearch.tsx
  src/web/views/EmployerListSearch/EmployerListSearchFilterProps.ts
  src/web/views/HeaderFooter/HeaderFooter.scss
Labels: bug, enhancement

#50 Add Arcadia Group profile and logo
  public/employers/arcadia.yml
  public/images/employers/arcadia.svg
Labels: information, verification needed

#52 Add country flags to employer cards
  public/images/flags/LICENSE
  public/images/flags/ca.svg
  public/images/flags/gb.svg
  public/images/flags/us.svg
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.tsx
Labels: enhancement

#54 Move employer-page action links into title bar
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.tsx
  src/web/views/EmployerDetailsHeader/__snapshots__/EmployerDetailsHeader.test.tsx.snap
  src/web/views/EmployerListDetails/__snapshots__/EmployerListDetails.test.tsx.snap
  src/web/views/EmployerPageDetails/EmployerPageDetails.tsx
  src/web/views/EmployerPageDetails/__snapshots__/EmployerPageDetails.test.tsx.snap
Labels: enhancement

#53 Add Marriott profile and logo
  public/employers/marriott.yml
  public/employers/sample.yml
  public/images/employers/marriott.svg
Labels: information, verification needed

#57 Add Partners HealthCare profile and logo
  public/employers/README.md
  public/employers/partners-healthcare.yml
  public/employers/sample.yml
  public/employers/target.yml
  public/employers/usps.yml
  public/images/employers/partners-healthcare.svg
  public/images/employers/target.png
  public/images/employers/target.svg
  public/images/employers/usps.svg
  src/__tests__/employer-records.test.ts
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerListDetails/EmployerListDetails.scss
  src/web/views/EmployerListSearch/EmployerListSearchFilter.ts
Labels: bug, information, infra, verification needed

#56 Add USPS profile and logo
  public/employers/usps.yml
Labels: information, verification needed

#51 Add CSEC (Calgary Flames) profile and logo
  public/employers/csec.yml
  public/images/employers/csec.svg
  public/strings/en-us.json
Labels: information, verification needed

#55 Add Honda profile and logo
  public/employers/honda.yml
  public/images/employers/honda.svg
  public/images/flags/jp.svg
  public/strings/en-us.json
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
Labels: information, verification needed

#58 Add profiles and logos for Nike and UA
  public/employers/nike.yml
  public/employers/under-armour.yml
  public/images/employers/nike.svg
  public/images/employers/under-armour.svg
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.tsx
Labels: bug, information, verification needed

#60 Fix edit button not rendering when website is null
  src/web/views/EmployerActionLinks/EmployerActionLinks.tsx
  src/web/views/EmployerActionLinks/__snapshots__/EmployerActionLinks.test.tsx.snap
  src/web/views/EmployerDetailsHeader/__snapshots__/EmployerDetailsHeader.test.tsx.snap
  src/web/views/EmployerListDetails/__snapshots__/EmployerListDetails.test.tsx.snap
  src/web/views/EmployerPageDetails/__snapshots__/EmployerPageDetails.test.tsx.snap
Labels: bug

#62 Add Wells Fargo profile and logo
  public/employers/wells-fargo.yml
  public/images/employers/wells-fargo.svg
  src/index.ts
Labels: information, verification needed

#64 Switch from TSLint to ESLint
  .eslintrc.yml
  .github/workflows/react-ci-yarn.yml
  .vscode/settings.json
  package.json
  razzle.config.js
  src/__tests__/TestUtils.ts
  src/__tests__/employer-records.test.ts
  src/api/controllers/EmployersController.ts
  src/api/middleware/LocalizationMiddleware.ts
  src/api/storage/EmployerRecordLoader.ts
  src/api/storage/LocaleLoader.ts
  src/common/DesignHelpers.tsx
  src/common/EmployeeNumber.ts
  src/common/EmployerLocation.ts
  src/common/LocalizedStrings.ts
  src/server.tsx
  src/web/App.tsx
  src/web/state/AppState.ts
  src/web/state/ducks/employers/actions.ts
  src/web/state/ducks/employers/api.ts
  src/web/state/ducks/employers/reducers.ts
  src/web/state/ducks/employers/types.ts
  src/web/state/ducks/environment/reducers.ts
  src/web/state/ducks/localization/actions.ts
  src/web/state/ducks/localization/reducers.ts
  src/web/views/About/About.tsx
  src/web/views/About/__snapshots__/About.test.tsx.snap
  src/web/views/EmployerActionLinks/EmployerActionLinks.tsx
  src/web/views/EmployerActionLinks/__snapshots__/EmployerActionLinks.test.tsx.snap
  src/web/views/EmployerCitation/EmployerCitation.tsx
  src/web/views/EmployerDetail/EmployerDetail.tsx
  src/web/views/EmployerDetail/__snapshots__/EmployerDetail.test.tsx.snap
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.tsx
  src/web/views/EmployerListDetails/EmployerListDetails.test.tsx
  src/web/views/EmployerListDetails/EmployerListDetails.tsx
  src/web/views/EmployerListSearch/EmployerListSearch.tsx
  src/web/views/EmployerListSearch/EmployerListSearchFilter.ts
  src/web/views/HeaderFooter/HeaderMenu.tsx
  src/web/views/HeaderFooter/__snapshots__/HeaderMenu.test.tsx.snap
  tslint.json
  yarn.lock
Labels: infra

#65 Add pagination capability to employers API
  public/strings/en-us.json
  src/api/controllers/EmployersController.ts
  src/api/middleware/LocalizationMiddleware.ts
  src/common/EmployerLocation.test.ts
  src/common/EmployerLocation.ts
  src/common/EmployerRecord.test.ts
  src/common/EmployerRecord.ts
  src/common/LocalizedStrings.test.ts
  src/common/MimeTypes.ts
  src/common/WikipediaHelpers.test.ts
  src/common/http/HttpRequestHeaders.ts
  src/common/http/HttpResponseHeaders.ts
  src/web/state/ducks/employers/api.ts
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.tsx
  src/web/views/EmployerList/EmployerList.test.tsx
  src/web/views/EmployerList/EmployerList.tsx
  src/web/views/EmployerList/__snapshots__/EmployerList.test.tsx.snap
  src/web/views/Home/Home.tsx
  src/web/views/Home/__snapshots__/Home.test.tsx.snap
Labels: enhancement

#66 Add a bunch more component/snap tests
  src/__tests__/TestUtils.ts
  src/web/App.test.tsx
  src/web/views/About/About.test.tsx
  src/web/views/EmployerActionLinks/EmployerActionLinks.test.tsx
  src/web/views/EmployerActionLinks/__snapshots__/EmployerActionLinks.test.tsx.snap
  src/web/views/EmployerCitationList/EmployerCitationList.test.tsx
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.test.tsx
  src/web/views/EmployerDetailsHeader/__snapshots__/EmployerDetailsHeader.test.tsx.snap
  src/web/views/EmployerList/EmployerList.test.tsx
  src/web/views/EmployerList/__snapshots__/EmployerList.test.tsx.snap
  src/web/views/EmployerListDetails/EmployerListDetails.test.tsx
  src/web/views/EmployerListSearch/EmployerListFilterControl/EmployeeCountFilterControl.test.tsx
  src/web/views/EmployerListSearch/EmployerListFilterControl/InternationalTypeFilterControl.test.tsx
  src/web/views/EmployerListSearch/EmployerListSearch.test.tsx
  src/web/views/EmployerListSearchFiltersSelector/EmployerListSearchFiltersSelector.test.tsx
  src/web/views/EmployerListSearchFiltersSelector/__snapshots__/EmployerListSearchFiltersSelector.test.tsx.snap
  src/web/views/EmployerPageDetails/EmployerPageDetails.test.tsx
  src/web/views/EmployerPageDetails/__snapshots__/EmployerPageDetails.test.tsx.snap
  src/web/views/HeaderFooter/FooterMenu.test.tsx
  src/web/views/HeaderFooter/HeaderMenu.test.tsx
  src/web/views/Home/Home.test.tsx
Labels: infra

#63 Add info about Wells Fargo PPP
  public/employers/wells-fargo.yml
Labels: information, verification needed

#68 Add SNC, Getaway, and Twitter profiles and logos
  public/employers/snc-lavalin.yml
  public/employers/the-getaway.yml
  public/employers/twitter.yml
  public/images/employers/snc-lavalin.svg
  public/images/employers/the-getaway.png
  public/images/employers/twitter.svg
  src/web/views/EmployerList/EmployerList.tsx
  src/web/views/EmployerListSearch/EmployerListSearchFilter.ts
Labels: bug, information, verification needed

#69 Update amazon.yml
  public/employers/amazon.yml
Labels: information

#70 Clarify Marriott salary reduction statement
  public/employers/marriott.yml
Labels: information

#71 Add The Sand Bar profile and image
  public/employers/the-sand-bar.yml
  public/images/employers/the-sand-bar.jpg
Labels: information, verification needed

#72 Add information about furloughs and cuts at Tesla
  public/employers/tesla.yml
Labels: information, verification needed

#74 Add build step to CI action & fix WebPack asset sizes
  .github/workflows/react-ci-yarn.yml
  razzle.config.js
Labels: infra

#75 Add Markdown support
  package.json
  public/employers/3m.yml
  public/employers/README.md
  public/employers/airbnb.yml
  public/employers/amazon.yml
  public/employers/arcadia.yml
  public/employers/costco.yml
  public/employers/csec.yml
  public/employers/dominos.yml
  public/employers/fedex.yml
  public/employers/gamestop.yml
  public/employers/google.yml
  public/employers/hobby-lobby.yml
  public/employers/honda.yml
  public/employers/marriott.yml
  public/employers/mcdonalds.yml
  public/employers/microsoft.yml
  public/employers/nike.yml
  public/employers/partners-healthcare.yml
  public/employers/sample.yml
  public/employers/snc-lavalin.yml
  public/employers/starbucks.yml
  public/employers/target.yml
  public/employers/tesla.yml
  public/employers/the-getaway.yml
  public/employers/the-sand-bar.yml
  public/employers/twitter.yml
  public/employers/under-armour.yml
  public/employers/united-airlines.yml
  public/employers/usps.yml
  public/employers/walmart.yml
  public/employers/wells-fargo.yml
  public/strings/en-us.yml
  razzle.config.js
  src/__tests__/employer-records.test.ts
  src/common/CitationSource.test.ts
  src/common/CitationSource.ts
  src/server.tsx
  src/web/views/AboutPage/AboutPage.test.tsx
  src/web/views/AboutPage/AboutPage.tsx
  src/web/views/AboutPage/__snapshots__/AboutPage.test.tsx.snap
  src/web/views/BurgerMenu.scss
  src/web/views/EmployerCitation/EmployerCitation.scss
  src/web/views/EmployerCitation/EmployerCitation.tsx
  src/web/views/EmployerCitation/__snapshots__/EmployerCitation.test.tsx.snap
  src/web/views/EmployerListDetails/EmployerListDetails.tsx
  src/web/views/EmployerListDetails/__snapshots__/EmployerListDetails.test.tsx.snap
  src/web/views/EmployerPageDetails/EmployerPageDetails.tsx
  src/web/views/EmployerPageDetails/__snapshots__/EmployerPageDetails.test.tsx.snap
  src/web/views/HeaderFooter/HeaderFooter.scss
  src/web/views/HeaderFooter/HeaderMenu.tsx
  yarn.lock
Labels: enhancement

#76 Add profiles & logos for Apple, Comcast, and Caterpillar
  public/employers/apple.yml
  public/employers/caterpillar.yml
  public/employers/comcast.yml
  public/employers/microsoft.yml
  public/images/employers/apple.svg
  public/images/employers/caterpillar.svg
  public/images/employers/comcast.svg
  src/common/EmployerIndustry.ts
Labels: information, verification needed

#77 Fix some card formatting and i18n
  public/strings/en-us.yml
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerListDetails/EmployerListDetails.scss
  src/web/views/HomePage/HomePage.test.tsx
  src/web/views/HomePage/HomePage.tsx
  src/web/views/HomePage/__snapshots__/HomePage.test.tsx.snap
Labels: bug

#78 added UC Irvine
  public/employers/ucirvine.yml
  public/images/employers/ucirvine.svg
Labels: information

#79 Improve employer data tests to catch more issues
  .eslintrc.yml
  public/strings/en-us.yml
  src/__tests__/employer-records.test.ts
  src/common/EmployerIndustry.ts
Labels: infra

#80 Add logo background colors and tidy up some employers
  public/employers/README.md
  public/employers/airbnb.yml
  public/employers/mcdonalds.yml
  public/employers/snc-lavalin.yml
  public/employers/starbucks.yml
  public/employers/target.yml
  public/employers/ucirvine.yml
  src/__tests__/employer-records.test.ts
  src/common/EmployerRecordBase.ts
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.scss
  src/web/views/EmployerDetailsHeader/EmployerDetailsHeader.tsx
  src/web/views/EmployerDetailsHeader/__snapshots__/EmployerDetailsHeader.test.tsx.snap
Labels: enhancement, infra, verification needed

#81 Add BlackRock, Chipotle, Oyo, and Whole Foods
  public/employers/amazon.yml
  public/employers/blackrock.yml
  public/employers/chipotle.yml
  public/employers/oyo.yml
  public/employers/united-airlines.yml
  public/images/employers/blackrock.svg
  public/images/employers/chipotle.svg
  public/images/employers/oyo.svg
  public/images/employers/united-airlines.svg
  public/images/flags/in.svg
Labels: information, verification needed

#82 Force employer image name to match YAML name
  src/__tests__/employer-records.test.ts
Labels: infra

#83 Make initial page load look smoother
  src/server.tsx
  src/web/App.tsx
  src/web/views/HeaderFooter/HeaderFooter.scss
  src/web/views/HeaderFooter/HeaderMenu.tsx
  src/web/views/HomePage/HomePage.scss
  src/web/views/Overload/Overload.scss
  src/web/views/Overload/Overload.test.tsx
  src/web/views/Overload/Overload.tsx
  src/web/views/Overload/__snapshots__/Overload.test.tsx.snap
Labels: enhancement

#88 Add employer status and 'employees after' field
  public/employers/README.md
  src/__tests__/employer-records.test.ts
  src/api/storage/EmployerRecordLoader.ts
  src/common/Citation.test.ts
  src/common/Citation.ts
  src/common/CitationType.ts
  src/common/EmployerEmployeeProfile.ts
  src/common/EmployerRating.ts
  src/common/EmployerRecord.test.ts
  src/common/EmployerRecordBase.test.ts
  src/common/EmployerRecordBase.ts
  src/common/EmployerStatus.ts
Labels: enhancement, infra

#84 Add Nissan profile & logo
  public/employers/caterpillar.yml
  public/employers/honda.yml
  public/employers/nissan.yml
  public/images/employers/nissan.svg
Labels: information, verification needed

#85 Add Fiat Chrysler (FCA) profile & logo
  public/employers/fiat-chrysler.yml
  public/images/employers/fiat-chrysler.svg
  public/images/flags/nl.svg
Labels: information, verification needed

#86 Add profiles & logos for Gap and Ascena
  public/employers/ascena.yml
  public/employers/gap.yml
  public/employers/google.yml
  public/images/employers/ascena.png
  public/images/employers/gap.svg
Labels: information, verification needed

#89 Add AMC profile & logo
  public/employers/amc.yml
  public/images/employers/amc.svg
Labels: information, verification needed

#90 Add HMH/JSUMC and Subway profiles and update others
  public/employers/gap.yml
  public/employers/hackensack-meridian-health.yml
  public/employers/mcdonalds.yml
  public/employers/subway.yml
  public/employers/the-getaway.yml
  public/images/employers/hackensack-meridian-health.svg
  public/images/employers/subway.svg
  src/common/EmployerEmployeeProfile.ts
Labels: enhancement, information, verification needed

#92 Add a number of employers' profiles & logos
  public/employers/README.md
  public/employers/amazon.yml
  public/employers/best-buy.yml
  public/employers/costco.yml
  public/employers/gamestop.yml
  public/employers/home-depot.yml
  public/employers/in-n-out.yml
  public/employers/starbucks.yml
  public/employers/trader-joes.yml
  public/images/employers/best-buy.svg
  public/images/employers/home-depot.svg
  public/images/employers/in-n-out.svg
  public/images/employers/trader-joes.svg
  src/common/WikipediaHelpers.test.ts
  src/common/WikipediaHelpers.ts
Labels: bug, information, verification needed

#91 Add Giant-Landover profile & logo and an Amazon claim
  public/employers/ahold-delhaize.yml
  public/employers/amazon.yml
  public/images/employers/ahold-delhaize.svg
Labels: information, verification needed

#93 Add 16 employers' profiles & logos
  public/employers/3m.yml
  public/employers/albertsons.yml
  public/employers/allegis-group.yml
  public/employers/amazon.yml
  public/employers/apple.yml
  public/employers/chick-fil-a.yml
  public/employers/cvs.yml
  public/employers/darden-restaurants.yml
  public/employers/dillards.yml
  public/employers/dollar-general.yml
  public/employers/dollar-tree.yml
  public/employers/fresh-market.yml
  public/employers/gamestop.yml
  public/employers/gap.yml
  public/employers/google.yml
  public/employers/hobby-lobby.yml
  public/employers/jo-ann.yml
  public/employers/kroger.yml
  public/employers/mcdonalds.yml
  public/employers/michaels.yml
  public/employers/microsoft.yml
  public/employers/office-depot.yml
  public/employers/rent-a-center.yml
  public/employers/staples.yml
  public/employers/starbucks.yml
  public/employers/tesla.yml
  public/employers/usps.yml
  public/employers/walgreens.yml
  public/employers/walmart.yml
  public/images/employers/albertsons.svg
  public/images/employers/allegis-group.png
  public/images/employers/ascena.png
  public/images/employers/chick-fil-a.svg
  public/images/employers/cvs.svg
  public/images/employers/darden-restaurants.svg
  public/images/employers/dillards.svg
  public/images/employers/dollar-general.png
  public/images/employers/dollar-tree.svg
  public/images/employers/fresh-market.svg
  public/images/employers/jo-ann.jpg
  public/images/employers/kroger.svg
  public/images/employers/michaels.svg
  public/images/employers/office-depot.svg
  public/images/employers/rent-a-center.svg
  public/images/employers/staples.svg
  public/images/employers/walgreens.svg
  src/web/views/EmployerList/EmployerList.tsx
  src/web/views/EmployerListSearch/EmployerListSearchFilter.ts
Labels: bug, information, verification needed

#94 Add 5 employers' profiles
  public/employers/christiana-care-health-system.yml
  public/employers/dunkin-brands.yml
  public/employers/hackensack-meridian-health.yml
  public/employers/kroger.yml
  public/employers/mcdonalds.yml
  public/employers/papa-johns.yml
  public/employers/restaurant-brands-international.yml
  public/employers/yum-brands.yml
  public/images/employers/christiana-care-health-system.svg
  public/images/employers/dunkin-brands.png
  public/images/employers/papa-johns.svg
  public/images/employers/restaurant-brands-international.svg
  public/images/employers/yum-brands.svg
  src/web/views/EmployerList/EmployerList.scss
Labels: bug, information, verification needed

#97 Improve rating algorithm and add more tests
  public/strings/en-us.yml
  src/common/CitationType.ts
  src/common/DesignHelpers.test.tsx
  src/common/EmployeeNumber.test.ts
  src/common/EmployerEmployeeProfile.ts
  src/common/EmployerIndustry.ts
  src/common/EmployerRating.ts
  src/common/EmployerRecord.test.ts
  src/common/EmployerRecord.ts
  src/common/EmployerRecordBase.test.ts
  src/common/EmployerRecordMetadata.test.ts
  src/common/EmployerStatus.ts
  src/common/LocalizedStrings.test.ts
  src/common/WikipediaHelpers.test.ts
  src/common/__snapshots__/DesignHelpers.test.tsx.snap
Labels: bug, enhancement, infra, verification needed

#96 Add profiles for Mt Sinai, NJPW, and Ellen
  public/employers/amazon.yml
  public/employers/ellen-digital-ventures.yml
  public/employers/mount-sinai-health-system.yml
  public/employers/new-japan-pro-wrestling.yml
  public/employers/united-airlines.yml
  public/images/employers/ellen-digital-ventures.svg
  public/images/employers/mount-sinai-health-system.svg
  public/images/employers/new-japan-pro-wrestling.svg
Labels: information, verification needed

#98 Weight 'hearsay' less than other rating types
  public/employers/csec.yml
  public/strings/en-us.yml
  src/common/EmployerRecord.test.ts
  src/common/EmployerRecord.ts
  src/web/views/EmployerCitation/EmployerCitation.scss
  src/web/views/EmployerCitation/EmployerCitation.tsx
  src/web/views/EmployerCitation/__snapshots__/EmployerCitation.test.tsx.snap
Labels: enhancement

#100 Populate SSR page with employer data
  src/api/controllers/EmployersController.ts
  src/api/storage/EmployerRecordLoader.ts
  src/common/EmployerRecordMetadata.ts
  src/server.tsx
  src/web/state/ducks/employers/reducers.ts
Labels: enhancement

#101 Add Domino's claim from Reddit
  public/employers/dominos.yml
  public/employers/gamestop.yml
  public/employers/papa-johns.yml
  public/employers/pizza-hut.yml
  public/employers/the-getaway.yml
  public/images/employers/gamestop.png
  public/images/employers/gamestop.svg
Labels: information, verification needed

#99 Add Shake Shack profile & logo
  public/employers/shake-shack.yml
  public/images/employers/shake-shack.svg
  src/web/views/EmployerPage/EmployerPage.tsx
Labels: information, verification needed

#102 Add Ruth's Chris profile & logo
  public/employers/ruths-chris.yml
  public/images/employers/ruths-chris.svg
Labels: information, verification needed

#103 Fix a mobile rendering bug and employer tests
  public/employers/target.yml
  public/employers/whole-foods.yml
  src/__tests__/employer-records.test.ts
  src/web/views/HomePage/HomePage.scss
Labels: bug

#105 Add HomeTown Pharmacy (MI) profile & logo
  public/employers/hometown-pharmacy.yml
  public/images/employers/hometown-pharmacy.png
Labels: information, verification needed

#104 Add Disney profile & logo
  public/employers/disney.yml
  public/images/employers/disney.svg
  src/web/views/EmployerList/EmployerList.tsx
Labels: information, verification needed

#106 Add some store-status updates for GameStop
  public/employers/gamestop.yml
Labels: information, verification needed

#108 Add import ordering lint rules
  .eslintrc.yml
  src/api/controllers/EmployersController.ts
  src/api/controllers/IndustriesController.ts
  src/common/EmployerRecord.ts
  src/web/state/ducks/employers/selectors.ts
  src/web/state/ducks/localization/selectors.ts
  src/web/views/AboutPage/AboutPage.tsx
  src/web/views/BackToTopButton/BackToTopButton.tsx
  src/web/views/EmployerActionLinks/EmployerActionLinks.tsx
  src/web/views/EmployerList/EmployerList.test.tsx
  src/web/views/EmployerListSearch/EmployerListSearchFilterProps.ts
  src/web/views/EmployerPageDetails/EmployerPageDetails.tsx
  src/web/views/HeaderFooter/FooterMenu.tsx
  src/web/views/HeaderFooter/HeaderMenu.tsx
Labels: infra

#113 Limit the number of employer items loaded at a time
  public/strings/en-us.yml
  src/web/App.tsx
  src/web/views/EmployerCitation/EmployerCitation.tsx
  src/web/views/EmployerList/EmployerList.scss
  src/web/views/EmployerList/EmployerList.test.tsx
  src/web/views/EmployerList/EmployerList.tsx
  src/web/views/EmployerList/__snapshots__/EmployerList.test.tsx.snap
  src/web/views/EmployerListPage/EmployerListPage.tsx
  src/web/views/EmployerListPage/__snapshots__/EmployerListPage.test.tsx.snap
  src/web/views/EmployerListSearch/EmployerListSearch.scss
  src/web/views/EmployerListSearch/EmployerListSearch.test.tsx
  src/web/views/EmployerListSearch/EmployerListSearch.tsx
  src/web/views/EmployerListSearch/__snapshots__/EmployerListSearch.test.tsx.snap
  src/web/views/EmployerPage/EmployerPage.test.tsx
  src/web/views/EmployerPage/EmployerPage.tsx
  src/web/views/EmployerRoute/EmployerRoute.tsx
  src/web/views/EmployerRoute/EmployerRouteContext.ts
  src/web/views/HomePage/HomePage.scss
Labels: enhancement

#112 Update Ruth's Chris PPP loan situation
  public/employers/ruths-chris.yml
Labels: information, verification needed

#109 Update claims for Ellen and Tesla
  public/employers/ellen-digital-ventures.yml
  public/employers/tesla.yml
Labels: information, verification needed

#110 Add Cinemark, WWE, and some other claims
  public/employers/amazon.yml
  public/employers/cinemark.yml
  public/employers/gamestop.yml
  public/employers/the-cheesecake-factory.yml
  public/employers/walmart.yml
  public/employers/wwe.yml
  public/images/employers/cinemark.svg
  public/images/employers/wwe.svg
  src/common/EmployerRecordBase.ts
  src/web/views/EmployerLogo/__snapshots__/EmployerLogo.test.tsx.snap
Labels: information, verification needed

#111 Add 6 more employers
  public/employers/README.md
  public/employers/american-airlines.yml
  public/employers/bjs-wholesale-club.yml
  public/employers/cvs.yml
  public/employers/fiat-chrysler.yml
  public/employers/ford.yml
  public/employers/general-motors.yml
  public/employers/instacart.yml
  public/employers/netflix.yml
  public/employers/united-airlines.yml
  public/images/employers/american-airlines.svg
  public/images/employers/bjs-wholesale-club.svg
  public/images/employers/ford.svg
  public/images/employers/general-motors.svg
  public/images/employers/instacart.svg
  public/images/employers/netflix.svg
  public/strings/en-us.yml
  src/web/views/EmployerPageDetails/EmployerPageDetails.scss
  src/web/views/EmployerPageDetails/EmployerPageDetails.tsx
  src/web/views/EmployerPageDetails/__snapshots__/EmployerPageDetails.test.tsx.snap
Labels: enhancement, information, verification needed

#115 Convert some PNGs to SVGs
  public/employers/dunkin-brands.yml
  public/employers/jo-ann.yml
  public/images/employers/dunkin-brands.png
  public/images/employers/dunkin-brands.svg
  public/images/employers/jo-ann.jpg
  public/images/employers/jo-ann.svg
  src/__tests__/employer-records.test.ts
Labels: enhancement, infra

#116 Add details about Amazon hourly raise
  public/employers/amazon.yml
  public/employers/costco.yml
  public/employers/whole-foods.yml
Labels: information, verification needed

#119 Add employee diff text if "after" value specified
  public/strings/en-us.yml
  src/common/EmployerEmployeeProfile.test.ts
  src/common/EmployerEmployeeProfile.ts
  src/web/views/EmployerPageDetails/EmployerPageDetails.scss
  src/web/views/EmployerPageDetails/EmployerPageDetails.test.tsx
  src/web/views/EmployerPageDetails/EmployerPageDetails.tsx
  src/web/views/EmployerPageDetails/__snapshots__/EmployerPageDetails.test.tsx.snap
Labels: enhancement

#117 Add 4 new employees and update FAQs
  public/employers/_sample.yml
  public/employers/cinemark.yml
  public/employers/fidelity.yml
  public/employers/fresh-market.yml
  public/employers/groupon.yml
  public/employers/los-angeles-times.yml
  public/employers/royal-caribbean.yml
  public/employers/tesla.yml
  public/employers/twitter.yml
  public/employers/usps.yml
  public/employers/wells-fargo.yml
  public/images/employers/chick-fil-a.svg
  public/images/employers/fidelity.svg
  public/images/employers/ford.svg
  public/images/employers/fresh-market.svg
  public/images/employers/groupon.svg
  public/images/employers/home-depot.svg
  public/images/employers/los-angeles-times.svg
  public/images/employers/new-japan-pro-wrestling.svg
  public/images/employers/papa-johns.svg
  public/images/employers/partners-healthcare.svg
  public/images/employers/rent-a-center.svg
  public/images/employers/royal-caribbean.svg
  public/images/employers/tesla.svg
  public/images/employers/twitter.svg
  public/images/employers/wells-fargo.svg
  public/strings/en-us.yml
  src/__tests__/employer-records.test.ts
  src/common/EmployerIndustry.ts
  src/web/views/AboutPage/AboutPage.test.tsx
  src/web/views/AboutPage/AboutPage.tsx
  src/web/views/AboutPage/__snapshots__/AboutPage.test.tsx.snap
Labels: enhancement, information, verification needed

#118 Add 7 more employers
  public/employers/and-pizza.yml
  public/employers/annapurna-pictures.yml
  public/employers/grubhub.yml
  public/employers/hertz.yml
  public/employers/meredith.yml
  public/employers/opendoor.yml
  public/employers/servicenow.yml
  public/images/employers/and-pizza.svg
  public/images/employers/annapurna-pictures.png
  public/images/employers/grubhub.svg
  public/images/employers/hertz.svg
  public/images/employers/meredith.svg
  public/images/employers/opendoor.svg
  public/images/employers/servicenow.svg
Labels: information, verification needed

#120 Add HCA Midwest
  public/employers/hca-midwest-health.yml
  public/images/employers/hca-midwest-health.svg
Labels: information, verification needed

#121 Add JetBlue Airways
  public/employers/jetblue.yml
  public/employers/united-airlines.yml
  public/images/employers/jetblue.svg
Labels: information, verification needed

#123 Add 3 new healthcare companies
  public/employers/hartford-healthcare.yml
  public/employers/partners-healthcare.yml
  public/employers/stanford-health-care.yml
  public/employers/steward-health-care.yml
  public/images/employers/hartford-healthcare.svg
  public/images/employers/hca-midwest-health.svg
  public/images/employers/stanford-health-care.svg
  public/images/employers/steward-health-care.svg
Labels: information, verification needed

#124 Add claim about masks for Costco
  public/employers/costco.yml
Labels: information, verification needed

#122 Add Tyson Foods and Nathan's Famous
  public/employers/nathans-famous.yml
  public/employers/tyson-foods.yml
  public/images/employers/nathans-famous.svg
  public/images/employers/tyson-foods.svg
Labels: information, verification needed
